services:
  auth-service:
    build: .
    networks:
      - shared-network
      - authdb-network
    ports:
      - "6001:6001"
    container_name: auth-service
    depends_on:
      - auth-db
    environment:
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - SERVER_PORT=${SERVER_PORT}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
      - SPRING_JPA_DATABASE=${SPRING_JPA_DATABASE}
      - SPRING_JPA_DATABASE_PLATFORM=${SPRING_JPA_DATABASE_PLATFORM}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - BOOTSTRAP_SECRET_KEY=${BOOTSTRAP_SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SERVICE_ACCOUNTS=${SERVICE_ACCOUNTS}
      - SERVICE_SECRET_AUTH=${SERVICE_SECRET_AUTH}
      - SERVICE_SECRET_EMAIL=${SERVICE_SECRET_EMAIL}
      - SERVICE_SECRET_FILE=${SERVICE_SECRET_FILE}
      - SERVICE_SECRET_VAULT=${SERVICE_SECRET_VAULT}
      - SERVICE_SECRET_TEST=${SERVICE_SECRET_TEST}
      - SERVICE_SECRET_REACT=${SERVICE_SECRET_REACT}
  auth-db:
    image: 'postgres:13.1-alpine'
    container_name: auth-db
    networks:
      - authdb-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  authdb-network:
    external: true
  shared-network:
    external: true