version: '1.0.0'

services:
  app:
    build: .
    networks:
      - shared-network
      - authdb-network
    ports:
      - "6001:6001"
    container_name: auth-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - DOCKER_DEPLOYMENT=true
  db:
    image: 'postgres:13.1-alpine'
    container_name: auth-database
    networks:
      - authdb-network
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
networks:
  authdb-network:
    external: true
  shared-network:
    external: true