# Application name
spring.application.name=${SPRING_APPLICATION_NAME:authservice}

# Server port
server.port=${SERVER_PORT:6001}

# Logging
logging.level.com.strangequark=${LOGGING_LEVEL:INFO}

# DB config
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:10}
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:30}
spring.datasource.hikari.idle-timeout=${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT:600000}
spring.datasource.hikari.connection-timeout=${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}
spring.datasource.hikari.max-lifetime=${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:1800000}

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
spring.jpa.database=${SPRING_JPA_DATABASE:postgresql}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

# CORS origins
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:6080}

# Secret keys
ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
BOOTSTRAP_SECRET_KEY=${BOOTSTRAP_SECRET_KEY}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
SERVICE_SECRET_AUTH=${SERVICE_SECRET_AUTH}
logging.level.com.zaxxer.hikari=DEBUG
spring.jpa.show-sql=true
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.postgresql=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.springframework.transaction=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
spring.datasource.hikari.leak-detection-threshold=2000
spring.datasource.hikari.register-mbeans=true
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
logging.level.org.springframework.web=DEBUG
