package com.strangequark.authservice.authorization;

public enum AuthorizationType {
    AUTH_API_ACCESS,
    EMAIL_API_ACCESS,
    FILE_API_ACCESS,
    VAULT_API_ACCESS,
    TELEMETRY_API_ACCESS,
    TELEMETRY_READ_ACCESS,
    INVITATION_MANAGEMENT,
    USER_MANAGEMENT,
    AUTHORIZATION_MANAGEMENT,
    EMAIL_TEMPLATE_MANAGEMENT
}
